---
title: "ADPStudy"
author: "tingyuan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: 
    toc_depth: 3
    config:
      toc:
        collapse: subsubsection
---
# R기초
## R 소개
### R 프로그래밍 언어
#### R이란?
#### R특징
- 오픈소스 프로그램
- 우수한 그래픽 지원 기능
- 데이터 저장 방식
- 모든 운영체제에서 사용이 가능
- 표준 플랫폼
- 객체지향 언어와 함수형 언어의 특징을 모두 지님

### R 설치

## R 기본
### R 다루기
#### 패키지 사용하기
#### 스크립트 다루기
#### 편리한 기능

### R 기초
#### 변수 생성
#### 변수명 규칙
#### R의 기초 연산자

### 데이터 타입
#### 스칼라
##### 숫자형
##### 문자형
##### 논리형
##### 팩터형
##### NA/NULL/NAN/INF

#### 벡터
#### 행렬
#### 데이터프레임
#### 리스트
#### 배열
```{}
array(data=NA, dim=length(data), dimnames=NULL)
```

### 자주 사용하는 함수
### 데이터 입출력
### 사용자 정의 함수
#### 함수 정의 문법
```{}
function(인자1, 인자2, 인자3, ..., 인자n) {
  표현식1
  표현식2
  ... 표현식n
  return(반환값)
}
```
#### 함수 정의 예시
- 하나의 숫자를 입력받아 제곱값을 계산하는 함수를 생성해 보자. 

```{r}
fun1<-function(num) {
  return(num ^ 2)
}
fun1(2)
```

- 여러 숫자를 입력받아 합을 출력하는 함수를 생성해 보자.

```{r}
fun2<-function(...) {
  x<-sum(...)
  paste("합계: ", x)
}
fun2(2, 4, 6, 8, 10)
```

